import type { ReliabilityTier, SourceRecord } from './types'

/** §2 필수 정보 소스 + §26 신뢰도 Tier + §29 Source Admin 필드 */
export const SOURCES: SourceRecord[] = [
  // ---------- GLOBAL ----------
  {
    id: 'technomic',
    name: 'Technomic',
    region: 'GLOBAL',
    country: 'US',
    url: 'https://www.technomic.com/',
    rssUrl: null,
    reliabilityTier: 1,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
    note: 'RSS 미제공 — Insights 페이지 HTML 파싱',
  },
  {
    id: 'euromonitor',
    name: 'Euromonitor Consumer Foodservice',
    region: 'GLOBAL',
    country: 'UK',
    url: 'https://www.euromonitor.com/consumer-foodservice',
    rssUrl: null,
    reliabilityTier: 1,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
    note: 'RSS 미제공 — Articles 목록 HTML 파싱',
  },
  {
    id: 'circana',
    name: 'Circana Foodservice',
    region: 'GLOBAL',
    country: 'US',
    url: 'https://www.circana.com/intelligence/foodservice/',
    rssUrl: null,
    reliabilityTier: 1,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },

  // ---------- ASIA ----------
  {
    id: 'qsr-media-asia',
    name: 'QSR Media Asia',
    region: 'ASIA',
    country: 'SG',
    url: 'https://qsrmedia.asia/',
    rssUrl: 'https://qsrmedia.asia/rss.xml',
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'foodlink-japan',
    name: 'Foodlink News Japan',
    region: 'ASIA',
    country: 'JP',
    url: 'https://www.foodlink.co.jp/',
    rssUrl: null,
    reliabilityTier: 3,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'hotpepper-gaishoku',
    name: 'Hot Pepper Gourmet 外食総研',
    region: 'ASIA',
    country: 'JP',
    url: 'https://www.hotpepper.jp/ggs/',
    rssUrl: null,
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
    note: '월간 외식 시장 조사 리포트 — 지표성 데이터',
  },
  {
    id: 'jfnet',
    name: 'Japan Foodservice Association',
    region: 'ASIA',
    country: 'JP',
    url: 'https://www.jfnet.or.jp/',
    rssUrl: null,
    reliabilityTier: 1,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
    note: '월간 외식산업 시장동향조사 (매출·객수·객단가)',
  },
  {
    id: 'scmp-food',
    name: 'South China Morning Post — Food',
    region: 'ASIA',
    country: 'HK',
    url: 'https://www.scmp.com/lifestyle/food-drink',
    rssUrl: 'https://www.scmp.com/rss/94/feed',
    reliabilityTier: 3,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },

  // ---------- EUROPE ----------
  {
    id: 'restaurant-online',
    name: 'Restaurant Online',
    region: 'EUROPE',
    country: 'UK',
    url: 'https://www.restaurantonline.co.uk/',
    rssUrl: 'https://www.restaurantonline.co.uk/arc/outboundfeeds/rss/',
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'mca-insight',
    name: 'MCA Insight',
    region: 'EUROPE',
    country: 'UK',
    url: 'https://www.mca-insight.com/',
    rssUrl: null,
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
    note: '유료 구독 — 공개 헤드라인만 수집',
  },
  {
    id: 'the-caterer',
    name: 'The Caterer',
    region: 'EUROPE',
    country: 'UK',
    url: 'https://www.thecaterer.com/',
    rssUrl: 'https://www.thecaterer.com/rss/news',
    reliabilityTier: 3,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'hotrec',
    name: 'HOTREC Europe',
    region: 'EUROPE',
    country: 'BE',
    url: 'https://www.hotrec.eu/',
    rssUrl: null,
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
    note: '유럽 호텔·레스토랑·카페 협회 — 정책/규제 동향',
  },
  {
    id: 'restaurant-industry-uk',
    name: 'Restaurant Industry Magazine UK',
    region: 'EUROPE',
    country: 'UK',
    url: 'https://restaurantindustry.co.uk/',
    rssUrl: 'https://restaurantindustry.co.uk/feed/',
    reliabilityTier: 3,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },

  // ---------- AMERICAS ----------
  {
    id: 'restaurant-business',
    name: 'Restaurant Business',
    region: 'AMERICAS',
    country: 'US',
    url: 'https://www.restaurantbusinessonline.com/',
    rssUrl: 'https://www.restaurantbusinessonline.com/feed',
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'restaurant-dive',
    name: 'Restaurant Dive',
    region: 'AMERICAS',
    country: 'US',
    url: 'https://www.restaurantdive.com/',
    rssUrl: 'https://www.restaurantdive.com/feeds/news/',
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'nrn',
    name: "Nation's Restaurant News",
    region: 'AMERICAS',
    country: 'US',
    url: 'https://www.nrn.com/',
    rssUrl: 'https://www.nrn.com/rss.xml',
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'qsr-magazine',
    name: 'QSR Magazine',
    region: 'AMERICAS',
    country: 'US',
    url: 'https://www.qsrmagazine.com/',
    rssUrl: 'https://www.qsrmagazine.com/feed/',
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'fsr-magazine',
    name: 'FSR Magazine',
    region: 'AMERICAS',
    country: 'US',
    url: 'https://www.fsrmagazine.com/',
    rssUrl: 'https://www.fsrmagazine.com/feed/',
    reliabilityTier: 3,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'nra',
    name: 'National Restaurant Association',
    region: 'AMERICAS',
    country: 'US',
    url: 'https://restaurant.org/research-and-media/',
    rssUrl: null,
    reliabilityTier: 1,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
    note: 'Restaurant Performance Index 등 지표 리포트',
  },
  {
    id: 'restaurants-canada',
    name: 'Restaurants Canada',
    region: 'AMERICAS',
    country: 'CA',
    url: 'https://www.restaurantscanada.org/',
    rssUrl: null,
    reliabilityTier: 2,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
  {
    id: 'mercado-consumo',
    name: 'Mercado & Consumo Foodservice',
    region: 'AMERICAS',
    country: 'BR',
    url: 'https://mercadoeconsumo.com.br/categoria/foodservice/',
    rssUrl: 'https://mercadoeconsumo.com.br/feed/',
    reliabilityTier: 3,
    active: true,
    lastCrawledAt: null,
    lastSuccessAt: null,
    articleCount: 0,
  },
]

export const SOURCE_BY_NAME = new Map(SOURCES.map((s) => [s.name, s]))
export const SOURCE_BY_ID = new Map(SOURCES.map((s) => [s.id, s]))

/** §26 — Tier → Source Reliability 점수(0~100) */
export const TIER_SCORE: Record<ReliabilityTier, number> = {
  1: 98,
  2: 88,
  3: 74,
  4: 50,
}

export function tierOf(sourceName: string): ReliabilityTier {
  return SOURCE_BY_NAME.get(sourceName)?.reliabilityTier ?? 4
}

export function reliabilityScoreOf(sourceName: string): number {
  return TIER_SCORE[tierOf(sourceName)]
}

/** §26 — Tier 4는 기본적으로 메인 대시보드에 노출하지 않는다. */
export function isMainDashboardVisible(sourceName: string): boolean {
  return tierOf(sourceName) <= 3
}
